site_name: L Ruhlen
site_description: BUSINESS LOBSTERS
site_author: L Ruhlen

repo_url: https://github.com/lruhlen/lruhlen.github.io

theme:
    name: bootstrap4
    highlightjs: true
    hljs_languages:
        - yaml
        - django
        - python

nav:
    - Home: index.md
    - About: about.md

markdown_extensions:
    - toc:
        baselevel: 2

plugins:
    - search:
        separator: '[\s\-\.]+'
